### ISSUE TITLE
Uncaught CellError related exception

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/pmix#14]
## Description
Getting this:`TypeError: Unsupported type <class 'pmix.cell.CellError'> in write()`

More details in attached log file.

Can replicate by trying to merge either fo the qlang files in the attached zip into the attached SDP form.

## Attachments
[cell error.zip](https://github.com/PMA-2020/qlang/files/3564241/cell.error.zip)

**Comment by joeflack4** [comment]
Fixed or non-issue?

**Comment by jkpr** [comment]
Fixed. See the commit that fixes it.
